# Generated by Django 4.2.11 on 2026-05-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL amigável')),
                ('category', models.CharField(choices=[('competicoes', 'Competições'), ('workshops', 'Workshops'), ('projetos', 'Projetos'), ('eventos', 'Eventos'), ('novidades', 'Novidades')], max_length=20, verbose_name='Categoria')),
                ('summary', models.TextField(max_length=500, verbose_name='Resumo')),
                ('body', models.TextField(verbose_name='Conteúdo')),
                ('cover_image', models.ImageField(upload_to='blog/covers/', verbose_name='Imagem de capa')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Edital')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL amigável')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('rules', models.TextField(verbose_name='Regulamento/Regras')),
                ('document', models.FileField(upload_to='editais/documents/', verbose_name='Arquivo PDF')),
                ('image', models.ImageField(upload_to='editais/images/', verbose_name='Imagem')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('closed', 'Fechado'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Data de início')),
                ('end_date', models.DateTimeField(verbose_name='Data de término')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
