# Generated by Django 6.0.5 on 2026-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='supabase_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID no Supabase'),
        ),
        migrations.AddField(
            model_name='post',
            name='supabase_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID no Supabase'),
        ),
    ]
